---
abstract: 'Mashes up L<MouseX::Getopt|MouseX::Getopt> and L<App::Cmd|App::Cmd>.'
author:
  - 'Yuval Kogman <nothingmuch@woobling.org>'
  - 'Guillermo Roditi <groditi@cpan.org>'
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  Carp: 0
  Data::Dumper: 0
  File::Find: 0
  File::Temp: 0
  MouseX::ConfigFromFile: 0
  Scalar::Util: 0
  Test::More: 0.94
  Test::Output: 0
  YAML: 0
  perl: 5.004
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MouseX-App-Cmd
requires:
  App::Cmd: 0.3
  App::Cmd::Command: 0
  English: 0
  File::Basename: 0
  Getopt::Long::Descriptive: 0
  Modern::Perl: 0
  Mouse: 0.86
  Mouse::Object: 0
  MouseX::Getopt: 0.18
  Test::use::ok: 0
  perl: 5.010
  utf8: 0
resources:
  bugtracker: http://github.com/mjg/MouseX-App-Cmd/issues
  repository: git://github.com/mjg/mousex-app-cmd.git
version: 0.07
